spring:
  jwt:
    secret: akxpsfhglvmshtltmakdlzmwkznfkdlekflwhsskrlfdjsjanwhgdmssmRla
  data:
    redis:
      host: 158.179.162.157
      port: 16380
      password: project00
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 500MB
  config:
    activate:
      on-profile:
        dev
  datasource:
    url: jdbc:postgresql://158.179.162.157:5432/postgres?currentSchema=todo
    username: project
    password: "project00**"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true

        use_sql_comments: true
#로그
logging:
  level:
    root: INFO  # ← 이 부분 추가
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    com.project.my : DEBUG

#swagger api 문서
springdoc:
  swagger-ui:
    groups-order: desc
    operations-sorter: method
    path: /swagger-ui.html
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

error:
  printStackTrace: true